program: src/yahtzee_agent/__main__.py
method: bayes
metric:
  goal: maximize
  name: val/mean_total_score
parameters:
  epochs:
    values: [500]
  entropy_coeff_rolling_max:
    distribution: uniform
    min: 0.05
    max: 0.3
  entropy_coeff_rolling_min:
    distribution: uniform
    min: 0.01
    max: 0.1
  entropy_coeff_scoring_max:
    distribution: uniform
    min: 0.1
    max: 0.5
  entropy_coeff_scoring_min:
    distribution: uniform
    min: 0.001
    max: 0.02
  entropy_hold_period:
    distribution: uniform
    min: 0.2
    max: 0.5
  entropy_anneal_period:
    distribution: uniform
    min: 0.2
    max: 0.5
  learning_rate:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.005
  hidden_size:
    distribution: int_uniform
    min: 192
    max: 768
  num_hidden:
    values: [3, 4, 5]
  min_lr_ratio:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
  gamma_min:
    distribution: log_uniform_values
    min: 0.85
    max: 0.95
  dropout_rate:
    distribution: uniform
    min: 0.05
    max: 0.15
  critic_coeff:
    distribution: log_uniform_values
    min: 0.005
    max: 0.5
  games_per_batch:
    values: [4, 5, 8, 10, 13, 20, 26, 40, 52, 65, 104, 130, 260]
  phi_features:
    value: "dice_onehot,dice_counts,rolls_used,phase,has_earned_yahtzee,available_categories,percent_progress_towards_bonus"
    
early_terminate:
  type: hyperband
  s: 2
  eta: 2
  min_iter: 100